config/routes.rb
Rails.application.routes.draw do


  resources :messages do
    post 'send_message'
  end

  post '/sms' => 'messages#receive'

  root 'search#new'

  resources :parks do
    resources :activities do
      resources :events
    end
  end

  resources :participants
  resources :subscriptions, only: [:new, :create, :destroy]
  resources :users do
    resources :verifications, only: [:new, :create]
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :search, only: [:new, :create, :show]

  get '/activities/:id', to: 'activities#park_list', as: 'park_list'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post 'parks_near_by' => 'search#parks_near_by'
  post 'activity_near_by/:id' => 'activities#activity_near_by'
  post 'all_parks' => 'parks#all_parks'

end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :park_activities
  has_many :parks, through: :park_activities


  validates :name, presence: true

  # accepts_nested_attributes_for :parks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  has_many :attendees, class_name: "User", through: :participants, source: :user
  has_many :participants

  belongs_to :park_activity
  has_one :park, through: :park_activity
  has_one :activity, through: :park_activity

  validates :date_time, :user_id, :park_activity_id, :count, presence: true
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :event_id, :user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord



TWILIO_CLIENT = Twilio::REST::Client.new(ENV['twilio_account_sid'], ENV['twilio_auth_token'])
APP_NUMBER = Rails.application.secrets.twilio_num



  def self.receive_message(params)
  message = Message.create({
  body: params[:Body],
  to_num: params[:To],
  from_num: params[:From]
  })

  end



  def self.send_message(to, body, *subscription_id)
    TWILIO_CLIENT.messages.create(
      from: APP_NUMBER,
      to: to,
      body: body
    )
    message = Message.create(
      body: body,
      to_num: to,
      from_num: APP_NUMBER,

    )
    message
  end


  # TWILIO_CLIENT.messages.create(from: "+1 647-931-1815", to: '4164283530', body: 'test')

  def self.send_code(user, verification)
    body = "Here is your verification code: " + verification
    self.send_message(user.cell, body)
  end



end

app/models/park.rb
class Park < ApplicationRecord
  has_many :park_activities
  has_many :activities, through: :park_activities
  has_many :events, through: :park_activities
  validates :name, :address, presence: true
  # accepts_nested_attributes_for :activities
  geocoded_by :address       # can also be an IP address
  after_validation :geocode, :if => :address_changed?




  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end







end

app/models/park_activity.rb
class ParkActivity < ApplicationRecord
  belongs_to :park
  belongs_to :activity
  has_many :subscriptions
  has_many :events

  validates :park_id, :activity_id, presence: true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :event_id, :user_id, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :park_activity
  belongs_to :users

  has_one :park, through: :park_activity
  has_one :activity, through: :park_activity

  validates :park_activity_id, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader


  has_many :owned_events, class_name: "Event"
  has_many :subscriptions
  has_many :participants
  has_many :attended_events, class_name: "Event", through: :participants, source: :event

  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :username, presence: true
  validates :username, uniqueness: true

# methods used for user phone verification
  def self.generate
  rand(100000..999999).to_s
  end

  def self.send_confirmation_to(user)
  code = self.generate
  user.update(verification: code)
  Message.send_code(user, code)
  end









end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token


  def receive
    Message.receive_message(params)
  end


  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json

  def create
    @message = Message.new(message_params)

      if @message.save
        Message.send_message(message_params[:to_num], message_params[:body])
      else
        render root_path
      end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body, :to_num, :from_num, :subscription_id, :integer)
    end


end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    @parks = Park.all
  end

  def show
    @park = Park.find(params[:id])
    @park_activities = @park.activities
  end

  def all_parks
    @parks = Park.all
    gps = params[:latitude]+','+ params[:longitude]
    @parks.near(gps, 100).size
    respond_to do |format|
      format.json do
        render :json => @parks.near(gps, 100).reverse
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :require_login, only: [:index, :new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to new_user_verification_path(@user)
      # redirect_to user_path(:id)
    else
      render :new
    end
  end

  def edit
  @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(:id)
    else
      render :new
    end
  end

  def show
    unless current_user == nil
      @user = current_user

      # Pulls an array of a users active subscriptions
      @user_subscriptions = @user.subscriptions

      # Pulls a users owned events
      @owned_events = @user.owned_events

      # Pulls an array of a users current events they are attending
      @user_events = @user.attended_events
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destory
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :avatar, :username, :cell, :password, :password_confirmation)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/park_activity_helper.rb
module ParkActivityHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form_for [@message], url: '/send_message' do |f| %>

  <p><%= f.label :to %></p>
  <p><%= f.telephone_field :to_num %></p>
  <p><%= f.label :body %></p>
  <p><%= f.text_area :body %></p>
  <p><%= f.submit "Send Message" %></p>

<% end %>
</div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>To num</th>
      <th>From num</th>
      <th>Subscription</th>
      <th>Integer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.body %></td>
        <td><%= message.to_num %></td>
        <td><%= message.from_num %></td>
        <td><%= message.subscription_id %></td>
        <td><%= message.integer %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>To num:</strong>
  <%= @message.to_num %>
</p>

<p>
  <strong>From num:</strong>
  <%= @message.from_num %>
</p>

<p>
  <strong>Subscription:</strong>
  <%= @message.subscription_id %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @message.integer %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>