config/routes.rb
Rails.application.routes.draw do


  resources :messages do
    post 'send_message'
  end

  post '/sms' => 'messages#receive'

  root 'search#new'

  resources :parks do
    resources :activities do
      resources :events
    end
  end

  resources :participants
  resources :subscriptions, only: [:new, :create, :destroy]
  resources :users do
    resources :verifications, only: [:new, :create]
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :search, only: [:new, :create, :show]

  get '/activities/:id', to: 'activities#park_list', as: 'park_list'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post 'parks_near_by' => 'search#parks_near_by'
  post 'activity_near_by/:id' => 'activities#activity_near_by'
  post 'all_parks' => 'parks#all_parks'

end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :park_activities
  has_many :parks, through: :park_activities


  validates :name, presence: true

  # accepts_nested_attributes_for :parks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  has_many :attendees, class_name: "User", through: :participants, source: :user
  has_many :participants

  belongs_to :park_activity
  has_one :park, through: :park_activity
  has_one :activity, through: :park_activity

  validates :date_time, :user_id, :park_activity_id, :count, presence: true
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :event_id, :user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord



TWILIO_CLIENT = Twilio::REST::Client.new(ENV['twilio_account_sid'], ENV['twilio_auth_token'])
APP_NUMBER = Rails.application.secrets.twilio_num



  def self.receive_message(params)
  message = Message.create({
  body: params[:Body],
  to_num: params[:To],
  from_num: params[:From]
  })

  end



  def self.send_message(to, body, *subscription_id)
    TWILIO_CLIENT.messages.create(
      from: APP_NUMBER,
      to: to,
      body: body
    )
    message = Message.create(
      body: body,
      to_num: to,
      from_num: APP_NUMBER,

    )
    message
  end


  # TWILIO_CLIENT.messages.create(from: "+1 647-931-1815", to: '4164283530', body: 'test')

  def self.send_code(user, verification)
    body = "Here is your verification code: " + verification
    self.send_message(user.cell, body)
  end



end

app/models/park.rb
class Park < ApplicationRecord
  has_many :park_activities
  has_many :activities, through: :park_activities
  has_many :events, through: :park_activities
  validates :name, :address, presence: true
  # accepts_nested_attributes_for :activities
  geocoded_by :address       # can also be an IP address
  after_validation :geocode, :if => :address_changed?




  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end







end

app/models/park_activity.rb
class ParkActivity < ApplicationRecord
  belongs_to :park
  belongs_to :activity
  has_many :subscriptions
  has_many :events

  validates :park_id, :activity_id, presence: true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :event_id, :user_id, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :park_activity
  belongs_to :users

  has_one :park, through: :park_activity
  has_one :activity, through: :park_activity

  validates :park_activity_id, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader


  has_many :owned_events, class_name: "Event"
  has_many :subscriptions
  has_many :participants
  has_many :attended_events, class_name: "Event", through: :participants, source: :event

  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :username, presence: true
  validates :username, uniqueness: true

# methods used for user phone verification
  def self.generate
  rand(100000..999999).to_s
  end

  def self.send_confirmation_to(user)
  code = self.generate
  user.update(verification: code)
  Message.send_code(user, code)
  end









end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    @parks = Park.all
  end

  def show
    @park = Park.find(params[:id])
    @park_activities = @park.activities
  end

  def all_parks
    @parks = Park.all
    gps = params[:latitude]+','+ params[:longitude]
    @parks.near(gps, 100).size
    respond_to do |format|
      format.json do
        render :json => @parks.near(gps, 100).reverse
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :require_login, only: [:index, :new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to new_user_verification_path(@user)
      # redirect_to user_path(:id)
    else
      render :new
    end
  end

  def edit
  @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(:id)
    else
      render :new
    end
  end

  def show
    unless current_user == nil
      @user = current_user

      # Pulls an array of a users active subscriptions
      @user_subscriptions = @user.subscriptions

      # Pulls a users owned events
      @owned_events = @user.owned_events

      # Pulls an array of a users current events they are attending
      @user_events = @user.attended_events
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destory
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :avatar, :username, :cell, :password, :password_confirmation)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/park_activity_helper.rb
module ParkActivityHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/parks/index.html.erb
<img src="park_index.jpg" height=500px width=100%>

<h1> Park List</h1>
<div class="Park_List">

</div>
<div id="map_wrapper">
  <div id="map_canvas" class="mapping"></div>
</div>
<br>
</div>

app/views/parks/show.html.erb
<%=image_tag(@park.image, height: '500px', width: '100%') %>
<div class="Park_page">
  <div class="park_page_header">
    <h3><%= @park.name %></h3>
    <p><%= @park.address %></p>
  </div>

  <ul class = "activity_list">
  <% @park_activities.each do |activity| %>
    <button class = "activity">
      <%= image_tag activity.image,:class =>'img-circle' %>
      <%= link_to activity.name, park_activity_path(params[:id], activity.id) %></li>
    </button>
  <%end%>
  </ul>

  <div class="bottom_nav">
    <%= link_to "Back To Search Results", :back %>
  </div>

</div>

app/views/users/_form.html.erb
<div class="edit_form">
  <%= form_for @user do |f| %>
  <br>
  <% if @user.errors.any? %>
       <div class="alert alert-danger">
         <h4>Could not create user because:</h4>
         <ul>
           <% @user.errors.full_messages.each do |message| %><br>
             <%= message %>
           <% end %>
         </ul>
       </div>
     <% end %>

    <div class="field">
       <%= f.label :username %><br />
       <%= f.text_field :username %>
    </div>

    <div class="field">
       <%= f.label :cell %><br />
       <%= f.telephone_field :cell %>
    </div>

    <div class="field">
       <%= f.label :email %><br />
       <%= f.text_field :email %>
    </div>

    <div class="field">
       <%= f.label :avatar %><br />
       <%= f.file_field :avatar, title: "Please choose image" %>
    </div>

    <div class="field">
       <%= f.label :password %><br />
       <%= f.password_field :password %>
    </div>
    <div class="field">
       <%= f.label :password_confirmation %><br />
       <%= f.password_field :password_confirmation %>
    </div>

    <div class="field">
       <%= f.submit %>
    </div>
</div>

<% end %>

app/views/users/edit.html.erb
<div class="show_page_content">
  <br>
  <br>
  <br>
  <br>
  <h1> <%= @user.username%>'s Edit Page <h1>


  <%= render 'form', user: @user %>

  <br>
  <br>
  <%= link_to 'My Page', @user %> | <%= link_to 'Back', users_path %>
</div>

app/views/users/new.html.erb
<div class="sign_up">
<br>
<br>
<br>
<br>

  <h1>Sign up!</h1>

  <%= render 'form' %>

  <%= link_to 'Back', "http://localhost:3000/search/new" %>
</div>

app/views/users/show.html.erb
<div class="show_page_content">
  <% if @user.avatar != ""%>
    <div class="profile_pic"><%= image_tag @user.avatar,:class =>'img-circle' %> <br><br>

    </div>
  <% else %>
    <div><%= image_tag "default.jpg",:class =>'img-circle' %></div>
  <% end %>

  <h3 class="welcome_user">Welcome to <span style="font-family:rancho"><span style="font-size:35px">Parkie</span></span> <%=@user.username%>!</h3></div>

  <div class="user_subs_events">

    <div class="subscription_list">
      <% if @user_subscriptions.count == 0 %>
        <h5>We are a community based around Parks, make sure to have a look around and subscribe to your favourite events!</h5>
      <% else %>
        <h5>Your subscriptions</h5>
        <!-- <div class="subscription_item"> -->
          <% @user_subscriptions.each do |subscription| %>
              <p><%= subscription.activity.name %> @ <%= subscription.park.name %></p>
          <!-- <div class="subscribe_button"> -->
            <%= form_tag(subscription_path(id: subscription.id), method: 'delete') do %>
              <button class="subcribe_button" name="subscribe_button" type="submit">Unsubscribe</button>
          <!-- </div> -->
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="event_list">
      <div class="owned_event_list">
        <% if @owned_events.count != 0 %>
          <h5>Your events</h5>
          <% @owned_events.each do |event| %>
            <p class="user_p"><%= event.park_activity.activity.name %> @ <%= event.park_activity.park.name %>
              Starting @ <%=event.date_time.strftime(" %I:%M%p") %> with <%= pluralize(event.count, "person" ) %> attending!  <br><br>
            </p>
            <%= form_tag(park_activity_event_path(park_id: event.park.id, activity_id: event.activity.id, event: event), method: 'delete') do %>
            <button class="create_event_button" name="create_event_button" type="submit">Cancel this Event!</button>
            <% end %>
          <% end %>
        <% else %>
          <h5>Your events</h5>
          <p>You have not created any events</p>
        <% end %>
      </div>

      <div class="joined_event_list">
        <% if @user_events.count == 0 %>
          <h5>Events you're attending</h5>
          <p>You are not currently scheduled to attend any events...<p>
        <% else %>
          <h5>Here is a list of your events</h5>
          <% @user_events.each do |event| %>
            <p><%= event.park_activity.activity.name %> @ <%= event.park_activity.park.name %>
            => <%= event.owner.username %> will be there @ <%=event.date_time.strftime(" %I:%M%p")%> with <%=event.count%> people attending!</p>
            <%= form_tag(participant_path(event: event), method: 'delete') do %>
              <button class="join_event_button" name="join_event_button" type="submit">Cancel your attendance!</button>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="edit_user_form">
    <%= form_for @user do |f| %>
    <br>
    <% if @user.errors.any? %>
         <div class="alert alert-danger">
           <h4>Could not create user because:</h4>
           <ul>
             <% @user.errors.full_messages.each do |message| %><br>
               <%= message %>
             <% end %>
           </ul>
         </div>
       <% end %>

      <div class="field">
         <%= f.label :username %><br />
         <%= f.text_field :username %>
      </div>

      <div class="field">
         <%= f.label :cell %><br />
         <%= f.telephone_field :cell %>
      </div>

      <div class="field">
         <%= f.label :email %><br />
         <%= f.text_field :email %>
      </div>

      <div class="field">
         <%= f.label :avatar %><br />
         <%= f.file_field :avatar, title: "Please choose image" %>
      </div>

      <div class="field">
         <%= f.label :password %><br />
         <%= f.password_field :password %>
      </div>
      <div class="field">
         <%= f.label :password_confirmation %><br />
         <%= f.password_field :password_confirmation %>
      </div>

      <div class="field">
         <%= f.submit %>
      </div>
  </div>

  <% end %>

  <div class="bottom_nav"><a class="edit_profile">Edit</a> | <%= link_to 'Search', root_url %> | <%= link_to 'Verify my #', new_user_verification_path(@user) if @user.verification != 'verified' %>
  </div>
</div>