config/routes.rb
Rails.application.routes.draw do


  resources :messages do
    post 'send_message'
  end

  post '/sms' => 'messages#receive'

  root 'search#new'

  resources :parks do
    resources :activities do
      resources :events
    end
  end

  resources :participants
  resources :subscriptions, only: [:new, :create, :destroy]
  resources :users do
    resources :verifications, only: [:new, :create]
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :search, only: [:new, :create, :show]

  get '/activities/:id', to: 'activities#park_list', as: 'park_list'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post 'parks_near_by' => 'search#parks_near_by'
  post 'activity_near_by/:id' => 'activities#activity_near_by'
  post 'all_parks' => 'parks#all_parks'

end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :park_activities
  has_many :parks, through: :park_activities


  validates :name, presence: true

  # accepts_nested_attributes_for :parks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  has_many :attendees, class_name: "User", through: :participants, source: :user
  has_many :participants

  belongs_to :park_activity
  has_one :park, through: :park_activity
  has_one :activity, through: :park_activity

  validates :date_time, :user_id, :park_activity_id, :count, presence: true
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :event_id, :user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord



TWILIO_CLIENT = Twilio::REST::Client.new(ENV['twilio_account_sid'], ENV['twilio_auth_token'])
APP_NUMBER = Rails.application.secrets.twilio_num



  def self.receive_message(params)
  message = Message.create({
  body: params[:Body],
  to_num: params[:To],
  from_num: params[:From]
  })

  end



  def self.send_message(to, body, *subscription_id)
    TWILIO_CLIENT.messages.create(
      from: APP_NUMBER,
      to: to,
      body: body
    )
    message = Message.create(
      body: body,
      to_num: to,
      from_num: APP_NUMBER,

    )
    message
  end


  # TWILIO_CLIENT.messages.create(from: "+1 647-931-1815", to: '4164283530', body: 'test')

  def self.send_code(user, verification)
    body = "Here is your verification code: " + verification
    self.send_message(user.cell, body)
  end



end

app/models/park.rb
class Park < ApplicationRecord
  has_many :park_activities
  has_many :activities, through: :park_activities
  has_many :events, through: :park_activities
  validates :name, :address, presence: true
  # accepts_nested_attributes_for :activities
  geocoded_by :address       # can also be an IP address
  after_validation :geocode, :if => :address_changed?




  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end







end

app/models/park_activity.rb
class ParkActivity < ApplicationRecord
  belongs_to :park
  belongs_to :activity
  has_many :subscriptions
  has_many :events

  validates :park_id, :activity_id, presence: true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :event_id, :user_id, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :park_activity
  belongs_to :users

  has_one :park, through: :park_activity
  has_one :activity, through: :park_activity

  validates :park_activity_id, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader


  has_many :owned_events, class_name: "Event"
  has_many :subscriptions
  has_many :participants
  has_many :attended_events, class_name: "Event", through: :participants, source: :event

  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :username, presence: true
  validates :username, uniqueness: true

# methods used for user phone verification
  def self.generate
  rand(100000..999999).to_s
  end

  def self.send_confirmation_to(user)
  code = self.generate
  user.update(verification: code)
  Message.send_code(user, code)
  end









end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    @parks = Park.all
  end

  def show
    @park = Park.find(params[:id])
    @park_activities = @park.activities
  end

  def all_parks
    @parks = Park.all
    gps = params[:latitude]+','+ params[:longitude]
    @parks.near(gps, 100).size
    respond_to do |format|
      format.json do
        render :json => @parks.near(gps, 100).reverse
      end
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def new
    @parks = Park.all
    @activities = Activity.all

# @current_location = Park.near('361 Montrose Ave Toronto', 1.9)
  end


  def address
    @address = Park.find(params[:address])
    Geocode.search("@address")
  end

  def parks_near_by
    gps = params[:latitude]+','+ params[:longitude]
    Park.near(gps, 100).size
    respond_to do |format|
      format.json do
        render :json => Park.near(gps, 100).reverse
      end
    end
    # @parks.each do |park|
    #   park.nearbys(1.9).each do |near_park|
    #   link_to near_park.name near_park.distance.round(2) kms)
    # end
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :require_login, only: [:index, :new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to new_user_verification_path(@user)
      # redirect_to user_path(:id)
    else
      render :new
    end
  end

  def edit
  @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(:id)
    else
      render :new
    end
  end

  def show
    unless current_user == nil
      @user = current_user

      # Pulls an array of a users active subscriptions
      @user_subscriptions = @user.subscriptions

      # Pulls a users owned events
      @owned_events = @user.owned_events

      # Pulls an array of a users current events they are attending
      @user_events = @user.attended_events
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destory
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :avatar, :username, :cell, :password, :password_confirmation)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/park_activity_helper.rb
module ParkActivityHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/search/new.html.erb
<div id="search_new_video">
  <video id="frisbee" width=100% autoplay loop muted>
    <source src="frisbee.mov" type="video/mp4">
  </video>
</div>

<div class="welcome_text">
  <h3>Welcome to <span id="parkie">Parkie</span>!</h3>
  <p>We are a community of park lovers!</p>
  <div class="row">
    <div class="col-xs-6">
      <div class="search_container">
        <a href="#park_search"><p>search by</p>
        <h2>PARK</h2></a>
      </div>
    </div>
    <div class="col-xs-6">
        <div class="search_container">
          <a href="#activities_search"><p>search by</p>
          <h2>ACTIVITIES</h2></a>
        </div>
    </div>
  </div>
</div>

<div class="about_parkie">
  <div class="about_container">
    <div class="row">
      <div class="col-xs-4">
        <div class="about_icons">
          <img src="success.png" width=100px height=100px>
        </div>
        <div class="about_description">
          <h3>Subscribe</h3>
          <p>Subscribe to your favorite activities!</p>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="about_icons">
          <img src="calendar.png" width=100px height=100px>
        </div>
        <div class="about_description">
          <h3>Join or Create Events</h3>
          <p>Join others.....</p>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="about_icons">
          <img src="smartphone (1).png" width=100px height=100px>
        </div>
        <div class="about_description">
          <h3>Notify everyone!</h3>
          <p>We'll notify everyone for you!</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="parks_map_wrapper">
</div>

<div id="map_wrapper">
    <div id="map_canvas" class="mapping"></div>
</div>


<div class="park_search">
  <h4> <a id="park_search"></a>Search by PARK</h4>
</div>

<!-- Parks list is appended to this div from javascript file -->
<div id="parks_near_by"></div>

<div class="all_parks"><%= link_to 'See All Parks', parks_path %></div>
<div class="activity_search">
  <h4><a id="activities_search"></a>Search by ACTIVITIES</h4>
  <% @activities.each do |activity| %>
    <%= link_to park_list_path(activity.id), :action => 'go'  do %>
    <div class="col-sm-3">
      <div class="icons">
        <div class="activity_header"><%= image_tag activity.image,:class =>'img-circle' %>
          <h3><%= activity.name %></h3>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>