config/routes.rb
Rails.application.routes.draw do


  resources :messages do
    post 'send_message'
  end

  post '/sms' => 'messages#receive'

  root 'search#new'

  resources :parks do
    resources :activities do
      resources :events
    end
  end

  resources :participants
  resources :subscriptions, only: [:new, :create, :destroy]
  resources :users do
    resources :verifications, only: [:new, :create]
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :search, only: [:new, :create, :show]

  get '/activities/:id', to: 'activities#park_list', as: 'park_list'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post 'parks_near_by' => 'search#parks_near_by'
  post 'activity_near_by/:id' => 'activities#activity_near_by'
  post 'all_parks' => 'parks#all_parks'

end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :park_activities
  has_many :parks, through: :park_activities


  validates :name, presence: true

  # accepts_nested_attributes_for :parks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  has_many :attendees, class_name: "User", through: :participants, source: :user
  has_many :participants

  belongs_to :park_activity
  has_one :park, through: :park_activity
  has_one :activity, through: :park_activity

  validates :date_time, :user_id, :park_activity_id, :count, presence: true
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :event_id, :user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord



TWILIO_CLIENT = Twilio::REST::Client.new(ENV['twilio_account_sid'], ENV['twilio_auth_token'])
APP_NUMBER = Rails.application.secrets.twilio_num



  def self.receive_message(params)
  message = Message.create({
  body: params[:Body],
  to_num: params[:To],
  from_num: params[:From]
  })

  end



  def self.send_message(to, body, *subscription_id)
    TWILIO_CLIENT.messages.create(
      from: APP_NUMBER,
      to: to,
      body: body
    )
    message = Message.create(
      body: body,
      to_num: to,
      from_num: APP_NUMBER,

    )
    message
  end


  # TWILIO_CLIENT.messages.create(from: "+1 647-931-1815", to: '4164283530', body: 'test')

  def self.send_code(user, verification)
    body = "Here is your verification code: " + verification
    self.send_message(user.cell, body)
  end



end

app/models/park.rb
class Park < ApplicationRecord
  has_many :park_activities
  has_many :activities, through: :park_activities
  has_many :events, through: :park_activities
  validates :name, :address, presence: true
  # accepts_nested_attributes_for :activities
  geocoded_by :address       # can also be an IP address
  after_validation :geocode, :if => :address_changed?




  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end







end

app/models/park_activity.rb
class ParkActivity < ApplicationRecord
  belongs_to :park
  belongs_to :activity
  has_many :subscriptions
  has_many :events

  validates :park_id, :activity_id, presence: true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :event_id, :user_id, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :park_activity
  belongs_to :users

  has_one :park, through: :park_activity
  has_one :activity, through: :park_activity

  validates :park_activity_id, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader


  has_many :owned_events, class_name: "Event"
  has_many :subscriptions
  has_many :participants
  has_many :attended_events, class_name: "Event", through: :participants, source: :event

  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :username, presence: true
  validates :username, uniqueness: true

# methods used for user phone verification
  def self.generate
  rand(100000..999999).to_s
  end

  def self.send_confirmation_to(user)
  code = self.generate
  user.update(verification: code)
  Message.send_code(user, code)
  end









end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Park.find(params[:park_id]).activities
  end

  def show
    @activity = Activity.find(params[:id])
    @park = Park.find(params[:park_id])
    @park_activity = ParkActivity.find_by(park_id: params[:park_id], activity_id: params[:id])

    @park_activity_events = Event.where(park_activity_id: @park_activity)
    @upcoming_events = Event.where("park_activity_id = ? AND date_time BETWEEN ? AND ?", @park_activity, Date.today, 1.week.from_now)

    unless current_user == nil
      @subscription = Subscription.find_by(park_activity_id: @park_activity.id, user_id: current_user.id)
    end
  end

  def park_list
    @activity = Activity.find(params[:id])
    @park_list = @activity.parks
  end

  #add a format json, which returns a json list of parks.
  def activity_near_by
    @activity = Activity.find(params[:id])
    gps = params[:latitude]+','+ params[:longitude]
    @activity.parks.near(gps, 100).size
    respond_to do |format|
      format.json do
        render :json => @activity.parks.near(gps, 100).reverse
      end
    end
  end


  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      redirect_to root_url
    else
      render :index
    end
  end

  private
  def activity_params
    params.require(:activity).permit(:name)
  end

end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    @parks = Park.all
  end

  def show
    @park = Park.find(params[:id])
    @park_activities = @park.activities
  end

  def all_parks
    @parks = Park.all
    gps = params[:latitude]+','+ params[:longitude]
    @parks.near(gps, 100).size
    respond_to do |format|
      format.json do
        render :json => @parks.near(gps, 100).reverse
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :require_login, only: [:index, :new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to new_user_verification_path(@user)
      # redirect_to user_path(:id)
    else
      render :new
    end
  end

  def edit
  @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(:id)
    else
      render :new
    end
  end

  def show
    unless current_user == nil
      @user = current_user

      # Pulls an array of a users active subscriptions
      @user_subscriptions = @user.subscriptions

      # Pulls a users owned events
      @owned_events = @user.owned_events

      # Pulls an array of a users current events they are attending
      @user_events = @user.attended_events
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destory
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :avatar, :username, :cell, :password, :password_confirmation)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/park_activity_helper.rb
module ParkActivityHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/index.html.erb
<div class="page-content">
  <div class="Activities_List">
    <div class="Container">
      <% @activities.each do |activity| %>
        <%= link_to park_activity_path(params[:park_id], activity.id), :action => 'go' do %>
          <h3><%= activity.name %></h3>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/activities/park_list.html.erb
<div class="page-content">

<div class="activity_list_img"><%=image_tag(@activity.image, height: '80px', width: '80px') %></div>
<br><br>
<div class="activity_near_by">
  <div class="activities_park_list">
    <div id="map_wrapper">
      <div id="map_canvas" class="mapping"></div>
    </div>
    <br>
  </div>
</div>

app/views/activities/show.html.erb
<div class="activity_show_img"><%=image_tag(@park_activity.image, height: '500px', width: '100%') %></div>

<h3 class="activity_header"><%=@activity.name %> at <%= @park.name %>!</h3>

<div class="subscription">
  <div class="subscription_container">
    <% if @subscription == nil %>
      <%= form_tag(subscriptions_path, method: 'post') do %>
        <%= hidden_field_tag(:park_activity_id, @park_activity.id) %>
        <h3>Subscribe to be notified of any upcoming events! </h3>
        <button class="subscribe_button" name="subscribe_button" type="submit">Subscribe!</button>
      <% end %>
    <% else %>
        <%= form_tag(subscription_path(id: @subscription.id), method: 'delete') do %>
          <h3>Subscribe to be notified of any upcoming events! </h3>
          <button class="subscribe_button" name="subscribe_button" type="submit">Unsubscribe</button>
        <% end %>
    <% end %>
  </div>
</div>

<div class="events">
  <div class="create_event">
    <img src="/assets/smartphone.png" width=80px height=80px>
    <h3>Create your own event, </br> and we'll notify everyone for you!</h3>
    <button class="create_event_button"><%= link_to "Create Event!", new_park_activity_event_path(params[:park_id], @activity.id) %></button>
  </div>

  <div class="events_list">
  <h2>Events from today until <%=1.week.from_now.strftime("%B %d, %Y")%>  </h2>
    <% if @upcoming_events == [] %>
      <h3>There are no scheduled events at this week.</h3>
    <% else %>
      <% @upcoming_events.each do |event| %>
        <div class="event_container">

          <h3><%= event.owner.username %> will be there @ <%=event.date_time.strftime("%B, %d, %I:%M%p")%> with <%=event.count%> people!<h3>

          <% unless current_user == nil %>
            <% if event.attendees.ids.include? current_user.id %>
              <%= form_tag(participant_path(event: event), method: 'delete') do %>
                <button class="attend_event_button" name="attend_event_button" type="submit">Cancel your attendance!</button>
              <% end %>
            <% elsif current_user.id == event.owner.id %>
              <%= form_tag(park_activity_event_path(park_id: event.park.id, activity_id: event.activity.id, event: event), method: 'delete') do %>
              <button class="create_event_button" name="create_event_button" type="submit">Cancel this Event!</button>
              <% end %>
            <% else %>
              <%= form_tag(participants_path, method: 'post') %>
              <%= hidden_field_tag(:event, event.id) %>
              <button class="attend_event_button" name="attend_event_button" type="submit">Attend this event!</button>

            <% end %>
          <% end %>
        </div>
      <% end %>
    <%end%>
  </div>

</div>